### ISSUE TITLE
Errors in running the simple example provided by the tutorial website

### ISSUE THREAD

**Issue by woshijamess** [dgehringer/sqsgenerator#29]
When running the simple example:  an ideal Re0.5W0.5 solution, errors always occurs as: 
"
(sqsgen) Qiangs-MacBook-Pro:file qiangbai$ sqsgen run iteration re-w.first.yaml
AttributeError: 'tuple' object has no attribute '__class__'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/qiangbai/anaconda3/envs/sqsgen/bin/sqsgen", line 11, in <module>
    sys.exit(cli())
  File "/Users/qiangbai/anaconda3/envs/sqsgen/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/qiangbai/anaconda3/envs/sqsgen/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/qiangbai/anaconda3/envs/sqsgen/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/qiangbai/anaconda3/envs/sqsgen/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/qiangbai/anaconda3/envs/sqsgen/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/qiangbai/anaconda3/envs/sqsgen/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/qiangbai/anaconda3/envs/sqsgen/lib/python3.10/site-packages/sqsgenerator/commands/common.py", line 88, in _inner
    result = f(*args, **kwargs)
  File "/Users/qiangbai/anaconda3/envs/sqsgen/lib/python3.10/site-packages/sqsgenerator/commands/common.py", line 130, in _dummy
    settings = process_settings(settings, params=process, ignore=ignore)
  File "/Users/qiangbai/anaconda3/envs/sqsgen/lib/python3.10/site-packages/sqsgenerator/settings/readers.py", line 296, in process_settings
    settings[param] = processor(settings)
  File "/Users/qiangbai/anaconda3/envs/sqsgen/lib/python3.10/site-packages/sqsgenerator/settings/functional.py", line 43, in _wrapped
    try: processed_value = f(settings)
  File "/Users/qiangbai/anaconda3/envs/sqsgen/lib/python3.10/site-packages/sqsgenerator/settings/readers.py", line 103, in read_structure
    structure = Structure(lattice, coords, species, (True, True, True))
  File "/Users/qiangbai/anaconda3/envs/sqsgen/lib/python3.10/site-packages/sqsgenerator/core/structure.py", line 40, in __init__
    super(Structure, self).__init__(lattice, frac_coords, symbols, pbc)
SystemError: <method-wrapper '__iter__' of list object at 0x1130e1080> returned a result with an exception set
"

conda version: conda 4.12.0
python version: 3.10
OS: Mac OS 12.5.1

**Comment by dgehringer** [comment]
@woshijamess many thanks for bringing the problem up!

It seems that there's a problem with the call to the extension module! Looks like it fails to create the underlying object

You could verify this by executing:

```python
import numpy as np
from sqsgenerator.core.core import Structure
Structure(np.eye(3), np.array([[0.0,0.0,0.0]]), ["Fe"], (True, True, True))
```
and see what the exception is, that would help to examine the problem further!

There is one strange thing however. You stack trace states
**structure.py line 40:** `super(Structure, self).init(lattice, frac_coords, symbols, pbc)`. However, it line 40 should be `super(Structure, self).__init__(lattice, frac_coords, symbols, pbc)`, hence the underscores (`__`) are missing.
Were there changes made to the code?

**Comment by woshijamess** [comment]
Thanks for your reply.

"
>>> import numpy as np
>>> from sqsgenerator.core.core import Structure
>>> Structure(np.eye(3), np.array([[0.0,0.0,0.0]]), ["Fe"], (True, True, True))
AttributeError: 'tuple' object has no attribute '__class__'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: <method-wrapper '__iter__' of list object at 0x1114f10c0> returned a result with an exception set
"

Still the tuple error.

Also, recheck the code.

Yes, it is "super(Structure, self).__init__(lattice, frac_coords, symbols, pbc)"

**Comment by woshijamess** [comment]
Yes, it is "super(Structure, self).__init__(lattice, frac_coords, symbols, pbc)" It has the underscore.

**Comment by woshijamess** [comment]
Yes, it is "super(Structure, self)."__"init"__"(lattice, frac_coords, symbols, pbc)" It has the underscore but vanish when reply.

**Comment by dgehringer** [comment]
The bug should be fixed in the master branch. The also the [Anaconda packages](https://anaconda.org/conda-forge/sqsgenerator) should be fixed, as a new build is available!

@woshijamess again many thanks for bringing the issue up!

**Comment by woshijamess** [comment]
Thanks very much for your hardworking even on weekends. It is fixed now.
