### ISSUE TITLE
Error in systematic mode

### ISSUE THREAD

**Issue by dhoulek** [dgehringer/sqsgenerator#41]
Hi Dominik,

I am trying to run a systematic mode to simulate s pm-CrN in TiN/CrN superlattice. Since we have there only 8 Cr atoms, I wanted to try the systematic approach. 

This is my input.yaml:
```
structure:
  file: POSCAR_pm_1+4.vasp
  supercell: [1, 1, 1]
#iterations: 1e6
mode: systematic
which: Cr
composition:
  Cr: 4
  Mo: 4
```
`sqsgen compute total-permutations input.yaml` says only 70 iterations should be needed. However, when executing `sqsgen run iteration input.yaml`, I get the following error:

```
Traceback (most recent call last):
  File "/home/dholec/software/miniconda3/envs/sqs/bin/sqsgen", line 11, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/dholec/software/miniconda3/envs/sqs/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dholec/software/miniconda3/envs/sqs/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/dholec/software/miniconda3/envs/sqs/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dholec/software/miniconda3/envs/sqs/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dholec/software/miniconda3/envs/sqs/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dholec/software/miniconda3/envs/sqs/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dholec/software/miniconda3/envs/sqs/lib/python3.12/site-packages/sqsgenerator/commands/common.py", line 88, in _inner
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "/home/dholec/software/miniconda3/envs/sqs/lib/python3.12/site-packages/sqsgenerator/commands/common.py", line 132, in _dummy
    return f(settings, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dholec/software/miniconda3/envs/sqs/lib/python3.12/site-packages/sqsgenerator/commands/run.py", line 32, in iteration
    sqs_results, timings = pair_sqs_iteration(settings, minimal=minimal, similar=similar, log_level=log_level)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dholec/software/miniconda3/envs/sqs/lib/python3.12/site-packages/sqsgenerator/public.py", line 168, in pair_sqs_iteration
    iteration_settings = construct_settings(settings, False, structure=settings.structure[settings.which])
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dholec/software/miniconda3/envs/sqs/lib/python3.12/site-packages/sqsgenerator/settings/__init__.py", line 34, in construct_settings
    return IterationSettings(
           ^^^^^^^^^^^^^^^^^^
Boost.Python.ArgumentError: Python argument types in
    IterationSettings.__init__(IterationSettings, Structure, dict, numpy.ndarray, numpy.ndarray, numpy.ndarray, dict, NoneType, int, list, list, float, float, IterationMode, dict)
did not match C++ signature:
    __init__(_object*, sqsgenerator::python::StructurePythonWrapper, boost::python::dict, boost::python::numpy::ndarray, boost::python::numpy::ndarray, boost::python::numpy::ndarray, boost::python::dict, boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<0ul, 0ul, (boost::multiprecision::cpp_integer_type)1, (boost::multiprecision::cpp_int_check_type)0, std::allocator<unsigned long long> >, (boost::multiprecision::expression_template_option)1>, int, boost::python::list, boost::python::list, double, double, sqsgenerator::iteration_mode, boost::python::dict)
```
Any idea, what may be causing this?

```
>sqsgen --version
sqsgenerator - A CLI tool to find optimized SQS structures
    version: 0.3
    build: 87c0c64df2edf2860b2ff658fb080f962162d91c@HEAD
    features: ['openmp']
    
    author: Dominik Gehringer
    email: dominik.gehringer@unileoben.ac.at
    repo: https://github.com/dgehringer/sqsgenerator
    docs: https://sqsgenerator.readthedocs.io/en/latest
    modules: ('ase-3.22.1', 'rich', 'json', 'yaml-6.0.1', 'pickle')
```

[POSCAR_pm_1+4.vasp.gz](https://github.com/dgehringer/sqsgenerator/files/15197181/POSCAR_pm_1%2B4.vasp.gz)

**Comment by dgehringer** [comment]
Many thanks for the detailed report! It strongly looks like there's a `None` passed where it shouldn't!

**Comment by dgehringer** [comment]
An  [updated version](https://anaconda.org/conda-forge/sqsgenerator/files) is through the CI/CD

**Comment by realitychemist** [comment]
My colleague and I are experiencing this bug in the most recent version. Our installed version is 0.3-py312h7ff606e_8 (win-64), which seems to be the latest version available. Is this a regression in the newer version?

**Comment by dgehringer** [comment]
Many thanks for your report I'm trying to fix it asap
