### ISSUE TITLE
"Installation Issue with SQSgen Due to Version Incompatibility

### ISSUE THREAD

**Issue by nanoparticals** [dgehringer/sqsgenerator#44]
Hello, I would like to ask for your help. When I was installing SQSgen, I encountered an issue with version incompatibility: undefined symbol: _ZN5boost3log11v2_mt_posix5sinks26basic_text_ostream_backendIcE7consumeERKNS1_11record_viewERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE. 
The versions I have installed are as follows: Could you please recommend the versions of the libraries I should download?

Python 3.9.19
Boost 1.75
Numpy 1.21.6
g++ (GCC) 4.8.5
mpirun (Open MPI) 4.1.6

**Comment by nanoparticals** [comment]
The specific error message is as follows:
sqsgen --version
Traceback (most recent call last):
  File "/home/haoxw/anaconda3/envs/sqsgen/bin/sqsgen", line 5, in <module>
    from sqsgenerator.cli import cli
  File "/home/haoxw/anaconda3/envs/sqsgen/lib/python3.9/site-packages/sqsgenerator/__init__.py", line 2, in <module>
    import sqsgenerator.cli
  File "/home/haoxw/anaconda3/envs/sqsgen/lib/python3.9/site-packages/sqsgenerator/cli.py", line 4, in <module>
    from sqsgenerator.commands.run import run
  File "/home/haoxw/anaconda3/envs/sqsgen/lib/python3.9/site-packages/sqsgenerator/commands/run.py", line 7, in <module>
    from sqsgenerator.commands.export import export_structures
  File "/home/haoxw/anaconda3/envs/sqsgen/lib/python3.9/site-packages/sqsgenerator/commands/export.py", line 7, in <module>
    from sqsgenerator.public import extract_structures
  File "/home/haoxw/anaconda3/envs/sqsgen/lib/python3.9/site-packages/sqsgenerator/public.py", line 11, in <module>
    from sqsgenerator.settings.readers import read_structure
  File "/home/haoxw/anaconda3/envs/sqsgen/lib/python3.9/site-packages/sqsgenerator/settings/__init__.py", line 5, in <module>
    from sqsgenerator.settings.defaults import defaults
  File "/home/haoxw/anaconda3/envs/sqsgen/lib/python3.9/site-packages/sqsgenerator/settings/defaults.py", line 9, in <module>
    from sqsgenerator.settings.functional import const, if_
  File "/home/haoxw/anaconda3/envs/sqsgen/lib/python3.9/site-packages/sqsgenerator/settings/functional.py", line 4, in <module>
    from sqsgenerator.core import get_function_logger
  File "/home/haoxw/anaconda3/envs/sqsgen/lib/python3.9/site-packages/sqsgenerator/core/__init__.py", line 6, in <module>
    from sqsgenerator.core.core import SQSResult, Atom
ImportError: /home/haoxw/anaconda3/envs/sqsgen/lib/python3.9/site-packages/sqsgenerator/core/core.so: undefined symbol: _ZN5boost3log11v2_mt_posix5sinks26basic_text_ostream_backendIcE7consumeERKNS1_11record_viewERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

**Comment by dgehringer** [comment]
Hi @nanoparticals 

Did you install it by compiling it yourself or did  you use `conda` to install it?
Is that is on MacOs or Linux?
Do you have the option to use a newer Python version? Currently the binaries are build against boost 1.8.4 ([see here](https://github.com/search?q=repo%3Adgehringer%2Fsqsgenerator-feedstock%20boost&type=code))

**Comment by nanoparticals** [comment]
Thank you very much for your response! 
I will update the Boost library and Python.
